"""
Seller Compatibility Routes
Allows a seller to retrieve the compatibility advice generated by their manager.
"""
from fastapi import APIRouter, Depends
from motor.motor_asyncio import AsyncIOMotorDatabase

from core.database import get_db
from core.security import get_current_seller

router = APIRouter()


@router.get("/compatibility-advice")
async def get_seller_compatibility_advice(
    current_user: dict = Depends(get_current_seller),
    db: AsyncIOMotorDatabase = Depends(get_db),
):
    """Return the latest compatibility advice generated by the manager for this seller."""
    seller_id = current_user["id"]
    manager_id = current_user.get("manager_id")
    query: dict = {"seller_id": seller_id}
    if manager_id:
        query["manager_id"] = manager_id
    record = await db["compatibility_advices"].find_one(
        query,
        {"_id": 0},
    )
    if not record:
        return {"advice": None}
    return {"advice": record.get("advice"), "generated_at": record.get("generated_at")}
