"""
Configuration and limits module
"""
from config.limits import (
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    MONGODB_MAX_POOL_SIZE,
    MONGODB_MIN_POOL_SIZE,
    RATE_LIMIT_AI,
    RATE_LIMIT_READ,
    RATE_LIMIT_WRITE,
    DEBRIEFS_LIMIT,
    MAX_QUERY_RESULTS,
    JWT_EXPIRATION_HOURS,
    PASSWORD_RESET_TOKEN_EXPIRATION_SECONDS
)

__all__ = [
    'DEFAULT_PAGE_SIZE',
    'MAX_PAGE_SIZE',
    'MONGODB_MAX_POOL_SIZE',
    'MONGODB_MIN_POOL_SIZE',
    'RATE_LIMIT_AI',
    'RATE_LIMIT_READ',
    'RATE_LIMIT_WRITE',
    'DEBRIEFS_LIMIT',
    'MAX_QUERY_RESULTS',
    'JWT_EXPIRATION_HOURS',
    'PASSWORD_RESET_TOKEN_EXPIRATION_SECONDS',
]
